### ISSUE TITLE
Move to Contributte

### ISSUE THREAD

**Issue by petrparolek** [contributte/pdf#39]
@f3l1x @castamir I recommend fork this repo by Contributte organization and this package mark as abandoned on packagist.

**Comment by petrparolek** [comment]
https://github.com/Joseki/PdfResponse/tree/contributte I rewrite readme in Contribute style.

**Comment by castamir** [comment]
I'm not using nor maintaining this repo anymore. Feel free to fork it. Let me know if you need something from me.

**Comment by petrparolek** [comment]
ping @f3l1x

**Comment by f3l1x** [comment]
Hi guys. Thank you @castamir for your work. Could you please make me a owner of this repository, that allows me to move under contributte organization. @petrparolek would be a new maintainer on your side. 

If you both agree.

**Comment by petrparolek** [comment]
Let me know, I will merge this https://github.com/Joseki/PdfResponse/tree/contributte branch to master and update name of composer package  in readme and in composer.json

**Comment by castamir** [comment]
@f3l1x GitHub did not allow me to transfer this repo to either Componette (I'm not a member with create repo permission) or to you (I can only transfer to my organization or my account at this time)

**Comment by petrparolek** [comment]
not Componette but Contributte

**Comment by castamir** [comment]
still a typo

> You don’t have the permission to create public repositories on contributte

**Comment by f3l1x** [comment]
Yep, that's right, I must be owner of this repository or member of Joseki org with transfer permission.

**Comment by petrparolek** [comment]
I think fork project is solution

**Comment by f3l1x** [comment]
Hi @castamir, I still cannot move repository to contributte, there is no button for it. Can you please allow it? :-)

**Comment by castamir** [comment]
Hi @f3l1x , I made you an admin of this organization. If this doesn't help, then fork it.

**Comment by f3l1x** [comment]
Done. Thank to all sides.

**Comment by petrparolek** [comment]
@castamir could you https://packagist.org/packages/joseki/pdf-response make as abandoned please? @f3l1x  could you make package contributte/pdf-response on packagist and change package name in composer.json please?

**Comment by f3l1x** [comment]
When we are doing such a refactoring/renaming, what about rename it to contributte/pdf? It could be more than PDF response. What do you think?

**Comment by petrparolek** [comment]
@f3l1x  are you planning new feautures?

**Comment by petrparolek** [comment]
@f3l1x thanks for creating new package on packagist.

**Comment by petrparolek** [comment]
@castamir  thanks for marking on packagist
