### ISSUE TITLE
Incorrect documentation of setting temp directory

### ISSUE THREAD

**Issue by LukasVaculcik** [contributte/pdf#60]
In documentation section [Configuration of custom temp dir for mPDF in PdfResponse](https://github.com/contributte/pdf/tree/master/.docs#configuration-of-custom-temp-dir-for-mpdf-in-pdfresponse)
Is example of setting configuration of tempDir that is not working.

I repost solution from [nette.org forum](https://forum.nette.org/cs/33966-contributte-pdfresponse-nefunguje-nastaveni-adresare-temp)

Configuration should be:
```
services:
  - Contributte\PdfResponse\PdfResponseFactory([tempDir: %tempDir%/pdf])
```
and then creation of response object in PHP should be like:
```
$response = $this->pdfResponseFactory->createResponse();
```
instead of
```
$response = new PdfResponse();
```

**Comment by f3l1x** [comment]
Updated. Thx.
